run:
  tests: true

issues:
  max-same-issues: 0
  exclude-rules:
    - path: cmd/links-service/main.go
      linters:
        - forbidigo
    - path: test
      linters:
        - testpackage

linters-settings:
  gci:
    sections:
      - standard
      - default

  godox:
    keywords:
      - FIXME
      - TODO

  lll:
    line-length: 130

  tagliatelle:
    case:
      rules:
        json: snake
        db: snake

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    #- depguard
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - gci
    - ginkgolinter
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilnil
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - typecheck
    - unconvert
    - unused
    - usestdlibvars
    - whitespace
    - wsl

    # Broken due to https://github.com/golangci/golangci-lint/issues/3711
    # - bodyclose
    # - contextcheck
    # - nilerr
    # - noctx
    # - rowserrcheck
    # - sqlclosecheck
    # - tparallel
    # - unparam
    # - wastedassign
